#!/usr/bin/env node
// Prepares the static files to put on Cloudflare, in deployment/cloudflare/public.
//
//   node tools/build_web/run.mjs
//
// WHY THIS WAY, AND NOT BY COPYING BY HAND
// The page does not exist as a file: server.mjs builds it in memory (the
// clientApp function is turned into text and served as /app.js).
// Copying it by hand would mean having two versions of the same page, and
// sooner or later they diverge — you fix a defect locally and online stays on
// the old one, without any error anywhere.
//
// So here we do the boring, safe thing: we start the real server on a service
// port, ask it for the page, and write to file exactly what it answers. It
// cannot diverge, because it is literally the same output as the one that runs
// locally and works.
//
// The only differences between local and online are the two patches below, and
// both FAIL LOUDLY if the text they are looking for is no longer there.
// A patch that silently does not apply is the worst defect there is: everything
// looks fine and online it is broken.

import { spawn } from 'node:child_process';
import { writeFileSync, mkdirSync, readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { recordableHabits } from '../habits.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT = join(ROOT, 'deployment/cloudflare/public');
const PORT = 3999;

// --- the patches -------------------------------------------------------------
const PATCHES = [
  {
    file: 'app.js',
    find: "fetch('/token')",
    put: "fetch('/token' + location.search)",
    why:
      'Online /token wants the password. It is in the address of the page ' +
      '(?k=...), so we pass it on to the token request. Locally the query is ' +
      'empty and nothing changes.',
  },
];

// --- the diary: the copy of the habits that runs on Cloudflare -----------------
// The online functions cannot read config/habits.json, because only what we send
// it goes onto Cloudflare. So a copy of it is written out as a module.
// GENERATED, never written by hand: a copy corrected by hand diverges from the
// original without anybody noticing, and it is the same reason why the page
// below is taken from the real server instead of being copied.
const PROFILE = process.env.PROFILE || '';
const HABITS_SRC = `config/profiles/${PROFILE}/habits.json`;

// A profile with no habits.json has no notebook, and that has to be a normal
// state rather than a crash: the generator does not produce habits yet, so
// every generated profile is in exactly this position.
function writeHabits() {
  const present = PROFILE && existsSync(join(ROOT, HABITS_SRC));
  const raw = present
    ? JSON.parse(readFileSync(join(ROOT, HABITS_SRC), 'utf8'))
    : { every_hours: 0, habits: [] };
  // The same translation the agent builder uses, so tools and backend agree.
  const src = { every_hours: raw.every_hours ?? 0, habits: recordableHabits(raw) };
  const text =
    (present
      ? `// GENERATED by tools/build_web/run.mjs from ${HABITS_SRC}.\n`
      : `// GENERATED by tools/build_web/run.mjs. No habits.json for the profile\n// "${PROFILE || '(not given)'}": the notebook is empty and the /diary routes\n// answer with no habits.\n`) +
    '// Do not edit by hand: at the next generation the edits disappear.\n\n' +
    `export const EVERY_HOURS = ${JSON.stringify(src.every_hours)};\n\n` +
    `export const HABITS = ${JSON.stringify(src.habits, null, 2)};\n`;
  mkdirSync(join(ROOT, 'deployment/cloudflare/lib'), { recursive: true });
  writeFileSync(join(ROOT, 'deployment/cloudflare/lib/habits.generated.js'), text);
  return present ? `${src.habits.length} generated for the diary` : 'none (the profile has no habits.json)';
}

console.log(`  habits       ${writeHabits()}`);

// --- start the real server, ask it for the page --------------------------------
const server = spawn(process.execPath, [join(ROOT, 'deployment/browser/server.mjs')], {
  cwd: ROOT,
  env: { ...process.env, AGENT: process.env.AGENT || PROFILE, PORT: String(PORT) },
  stdio: ['ignore', 'pipe', 'pipe'],
});

let error = '';
server.stderr.on('data', d => (error += d));

const ready = new Promise((resolve, reject) => {
  const timer = setTimeout(() => reject(new Error('the server did not answer within 20 seconds')), 20_000);
  server.stdout.on('data', d => {
    if (String(d).includes('Talk to it')) { clearTimeout(timer); resolve(); }
  });
  server.on('exit', code => {
    clearTimeout(timer);
    reject(new Error(`the server exited with code ${code}\n${error.trim()}`));
  });
});

try {
  await ready;

  const get = async path => {
    const res = await fetch(`http://localhost:${PORT}${path}`);
    if (!res.ok) throw new Error(`${path} answered ${res.status}`);
    return res.text();
  };

  const file = {
    'index.html': await get('/'),
    'app.js': await get('/app.js'),
  };

  for (const patch of PATCHES) {
    const before = file[patch.file];
    if (!before.includes(patch.find)) {
      throw new Error(
        `PATCH NOT APPLIED in ${patch.file}: cannot find ${patch.find}\n` +
        `  it was there for: ${patch.why}\n` +
        `  which means server.mjs has changed. Update the patch, do NOT remove it:\n` +
        `  without it, online the page cannot mint the token and the agent stays mute.`,
      );
    }
    file[patch.file] = before.split(patch.find).join(patch.put);
  }

  mkdirSync(OUT, { recursive: true });
  for (const [name, text] of Object.entries(file)) {
    writeFileSync(join(OUT, name), text);
    console.log(`  ${name.padEnd(12)} ${text.length} characters`);
  }

  // Final check: the key must NEVER end up in the static files.
  const key = process.env.ASSEMBLYAI_API_KEY;
  if (key && key.length > 8) {
    for (const [name, text] of Object.entries(file)) {
      if (text.includes(key)) throw new Error(`THE API KEY HAS ENDED UP IN ${name}. Do not publish.`);
    }
  }
  console.log('\n  the key does not appear in the static files: ok');
  console.log(`\nwritten in deployment/cloudflare/public`);
} finally {
  server.kill();
}
