#!/usr/bin/env node
// Prepares the static files to put on Cloudflare, in deployment/cloudflare/public.
//
//   node tools/build_web/run.mjs
//
// WHY THIS WAY, AND NOT BY COPYING BY HAND
// The page does not exist as a file: server.mjs builds it in memory (the
// clientApp function is turned into text and served as /app.js).
// Copying it by hand would mean having two versions of the same page, and
// sooner or later they diverge — you fix a defect locally and online stays on
// the old one, without any error anywhere.
//
// So here we do the boring, safe thing: we start the real server on a service
// port, ask it for the page, and write to file exactly what it answers. It
// cannot diverge, because it is literally the same output as the one that runs
// locally and works.
//
// The only differences between local and online are the two patches below, and
// both FAIL LOUDLY if the text they are looking for is no longer there.
// A patch that silently does not apply is the worst defect there is: everything
// looks fine and online it is broken.

import { spawn } from 'node:child_process';
import { createHash } from 'node:crypto';
import { writeFileSync, mkdirSync, readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { recordableHabits } from '../habits.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT = join(ROOT, 'deployment/cloudflare/public');
const PORT = 3999;

// --- the patches -------------------------------------------------------------
// EMPTY SINCE 24/09, and that is a fix, not a removal.
//
// There used to be one patch here, rewriting fetch('/token') into
// fetch('/token' + location.search), because online /token wants ?k=<PAGE_KEY>
// and locally it wants nothing. server.mjs now works that out for itself: the
// KEY constant at the top of clientApp reads the key from the address ONCE,
// remembers it, and is the empty string when there is no key — which is exactly
// what localhost needs. One behaviour in one place, so there is no longer a
// version of the page that only exists after a build step.
//
// Do not put the patch back. If online minting breaks, the thing to look at is
// KEY in server.mjs, and REQUIRED below is what fails the build if it is gone.
const PATCHES = [];

// --- what the built page must contain ------------------------------------------
// A patch that fails to apply stops the build (see the throw below). Deleting
// the patch removed that protection, so this replaces it: the same guarantee,
// stated as a fact about the output rather than as an edit to it.
const REQUIRED = [
  {
    file: 'app.js',
    text: "fetch('/token' + KEY)",
    why:
      'Online /token answers 401 without ?k=<PAGE_KEY>. Without this the agent ' +
      'stays mute on the public address and every backend check still passes.',
  },
  {
    file: 'app.js',
    text: 'localStorage.setItem(STORE, k)',
    why:
      'The key is remembered so it can be taken out of the address bar. Without ' +
      'it the address must carry ?k=... on every visit — which locked Claudia ' +
      'out twice on 24/09 and put the password on camera in the pitch video.',
  },
  {
    file: 'app.js',
    text: "url.searchParams.delete('k')",
    why:
      'This is what clears the key from the address bar. Without it the page ' +
      'still works and the secret is legible in every frame that films it.',
  },
];

// --- the diary: the copy of the habits that runs on Cloudflare -----------------
// The online functions cannot read config/habits.json, because only what we send
// it goes onto Cloudflare. So a copy of it is written out as a module.
// GENERATED, never written by hand: a copy corrected by hand diverges from the
// original without anybody noticing, and it is the same reason why the page
// below is taken from the real server instead of being copied.
const PROFILE = process.env.PROFILE || '';
const HABITS_SRC = `config/profiles/${PROFILE}/habits.json`;

// A profile with no habits.json has no notebook, and that has to be a normal
// state rather than a crash: the generator does not produce habits yet, so
// every generated profile is in exactly this position.
function writeHabits() {
  const present = PROFILE && existsSync(join(ROOT, HABITS_SRC));
  const raw = present
    ? JSON.parse(readFileSync(join(ROOT, HABITS_SRC), 'utf8'))
    : { every_hours: 0, habits: [] };
  // The same translation the agent builder uses, so tools and backend agree.
  const src = { every_hours: raw.every_hours ?? 0, habits: recordableHabits(raw) };
  const text =
    (present
      ? `// GENERATED by tools/build_web/run.mjs from ${HABITS_SRC}.\n`
      : `// GENERATED by tools/build_web/run.mjs. No habits.json for the profile\n// "${PROFILE || '(not given)'}": the notebook is empty and the /diary routes\n// answer with no habits.\n`) +
    '// Do not edit by hand: at the next generation the edits disappear.\n\n' +
    `export const EVERY_HOURS = ${JSON.stringify(src.every_hours)};\n\n` +
    `export const HABITS = ${JSON.stringify(src.habits, null, 2)};\n`;
  mkdirSync(join(ROOT, 'deployment/cloudflare/lib'), { recursive: true });
  writeFileSync(join(ROOT, 'deployment/cloudflare/lib/habits.generated.js'), text);
  return present ? `${src.habits.length} generated for the diary` : 'none (the profile has no habits.json)';
}

console.log(`  habits       ${writeHabits()}`);

// --- the greetings: the same copy, for the same reason -------------------------
// /token picks the opening line before every conversation and writes it onto the
// stored agent, so Cloudflare needs the list. A profile whose persona.json still
// has the old flat greeting list generates nothing and the agent simply keeps the
// one greeting it was published with — the behaviour before 22/09, not a crash.
const PERSONA_SRC = `config/profiles/${PROFILE}/persona.json`;
function writeGreetings() {
  const present = PROFILE && existsSync(join(ROOT, PERSONA_SRC));
  const g = present
    ? JSON.parse(readFileSync(join(ROOT, PERSONA_SRC), 'utf8')).greetings
    : null;
  const usable = g && g.introduction && g.rotation;
  const out = usable
    ? { timezone: g.timezone ?? 'UTC', bands: g.bands ?? {}, introduction: g.introduction, rotation: g.rotation }
    : null;
  const text =
    `// GENERATED by tools/build_web/run.mjs from ${PERSONA_SRC}.\n` +
    '// Do not edit by hand: at the next generation the edits disappear.\n' +
    (usable ? '' : '// This profile has no introduction/rotation greetings, so /token leaves\n// the agent\'s published greeting alone.\n') +
    '\n' +
    `export const GREETINGS = ${JSON.stringify(out, null, 2)};\n`;
  writeFileSync(join(ROOT, 'deployment/cloudflare/lib/greetings.generated.js'), text);
  if (!usable) return 'none (profile has no introduction/rotation)';
  const n = Object.values(out.rotation).reduce((a, l) => a + l.length, 0);
  return `1 introduction + ${n} in ${Object.keys(out.rotation).length} bands, ${out.timezone}`;
}

console.log(`  greetings    ${writeGreetings()}`);

// --- start the real server, ask it for the page --------------------------------
const server = spawn(process.execPath, [join(ROOT, 'deployment/browser/server.mjs')], {
  cwd: ROOT,
  env: { ...process.env, AGENT: process.env.AGENT || PROFILE, PORT: String(PORT) },
  stdio: ['ignore', 'pipe', 'pipe'],
});

let error = '';
server.stderr.on('data', d => (error += d));

const ready = new Promise((resolve, reject) => {
  const timer = setTimeout(() => reject(new Error('the server did not answer within 20 seconds')), 20_000);
  server.stdout.on('data', d => {
    if (String(d).includes('Talk to it')) { clearTimeout(timer); resolve(); }
  });
  server.on('exit', code => {
    clearTimeout(timer);
    reject(new Error(`the server exited with code ${code}\n${error.trim()}`));
  });
});

try {
  await ready;

  const get = async path => {
    const res = await fetch(`http://localhost:${PORT}${path}`);
    if (!res.ok) throw new Error(`${path} answered ${res.status}`);
    return res.text();
  };

  const file = {
    'index.html': await get('/'),
    'app.js': await get('/app.js'),
  };

  for (const patch of PATCHES) {
    const before = file[patch.file];
    if (!before.includes(patch.find)) {
      throw new Error(
        `PATCH NOT APPLIED in ${patch.file}: cannot find ${patch.find}\n` +
        `  it was there for: ${patch.why}\n` +
        `  which means server.mjs has changed. Update the patch, do NOT remove it:\n` +
        `  without it, online the page cannot mint the token and the agent stays mute.`,
      );
    }
    file[patch.file] = before.split(patch.find).join(patch.put);
  }

  for (const need of REQUIRED) {
    if (!file[need.file].includes(need.text)) {
      throw new Error(
        `MISSING FROM ${need.file}: ${need.text}\n` +
        `  it has to be there for: ${need.why}\n` +
        `  server.mjs has changed. Put it back, or update this check on purpose —\n` +
        `  do not delete it: this is the only thing standing between a rename and\n` +
        `  a deploy that passes every test and is dead on the public address.`,
      );
    }
  }
  console.log(`  ${REQUIRED.length} required strings present in the built page: ok`);

  // THE PAGE IS CACHED FOR FOUR HOURS AND ITS NAME NEVER CHANGES.
  //
  // 22/09: a deployed fix was live on the hash URL and on a cache-busted
  // request, while the custom domain — the address in the hackathon submission
  // — kept handing out the PREVIOUS app.js. Every backend check passed and the
  // site still looked broken. This is 6.2 in its purest form: the thing says it
  // deployed, and what people get is the old one.
  //
  // `_headers` does NOT fix it. Cloudflare Pages manages Cache-Control for
  // static assets itself and ignores the file for them: measured the same day,
  // `/` and `/index.html` come back `no-cache` because HTML always does, while
  // `/app.js` stays `max-age=14400` whatever `_headers` says. So the header
  // route is a dead end — do not try it again.
  //
  // What DOES work is changing the name when the content changes. index.html is
  // never cached, so a new index.html points at a URL nobody has ever fetched,
  // and the browser has no choice. Content-addressed, so an unchanged build
  // keeps the same URL and stays cached, which is the point.
  const stamp = createHash('sha256').update(file['app.js']).digest('hex').slice(0, 8);
  const ref = '<script src="/app.js"></script>';
  if (!file['index.html'].includes(ref)) {
    throw new Error(
      `cannot find ${ref} in index.html, so app.js cannot be given a version.\n` +
      '  Without it a deployed fix can sit invisible behind a four-hour cache.\n' +
      '  server.mjs has changed: update this, do NOT remove it.',
    );
  }
  file['index.html'] = file['index.html'].replace(ref, `<script src="/app.js?v=${stamp}"></script>`);
  console.log(`  app.js version ${stamp}`);

  mkdirSync(OUT, { recursive: true });
  for (const [name, text] of Object.entries(file)) {
    writeFileSync(join(OUT, name), text);
    console.log(`  ${name.padEnd(12)} ${text.length} characters`);
  }

  // Final check: the key must NEVER end up in the static files.
  const key = process.env.ASSEMBLYAI_API_KEY;
  if (key && key.length > 8) {
    for (const [name, text] of Object.entries(file)) {
      if (text.includes(key)) throw new Error(`THE API KEY HAS ENDED UP IN ${name}. Do not publish.`);
    }
  }
  console.log('\n  the key does not appear in the static files: ok');
  console.log(`\nwritten in deployment/cloudflare/public`);
} finally {
  server.kill();
}
