import React, {useCallback, useRef, useState} from 'react';
import {continueRender, delayRender, staticFile} from 'remotion';
import {theme} from './theme';

/**
 * The product's conversation page, laid out live by the browser every frame and
 * scrolled by us - not a screen recording, and not a mock-up.
 *
 * WHY IT IS NOT A RECORDING. Section 4 was cut from a capture first. The column
 * sat off-centre inside browser chrome, the page had only grown far enough to
 * fill its top half so the rest was dead white, and the start of the
 * conversation had scrolled away before the clip began. None of that can be
 * fixed afterwards: framing and scroll are decided when you press record.
 * Here the whole conversation exists at once, so the camera is ours.
 *
 * WHY IT IS NOT A MOCK-UP. public/pages/*.html is generated by
 * make-conversation.mjs from the product's own stylesheet, the markup app.js
 * builds class for class, and the stored timeline of a real session. Nobody
 * typed a line of that dialogue.
 *
 * The page renders at PAGE_W CSS pixels - the width the person's phone gives it
 * - and is scaled up for the screen, so the type is the product's own type at
 * its own proportions, just larger.
 */

export const PAGE_W = 620;

export type Lines = {
  docHeight: number;
  /** top of each .line in page pixels, in order */
  tops: number[];
  /** bottom of each .line, so a run of turns can be boxed rather than pointed at */
  bottoms: number[];
  /** what each line says, so a section can find its moment by WORDS rather than
   *  by a row number - an index silently points at the wrong line the day a
   *  turn is added, and nothing about the render would look broken. */
  texts: string[];
};

/** The top of the first line whose text matches, or 0. */
export const findLine = (l: Lines | null, re: RegExp) => {
  if (!l) return 0;
  const i = l.texts.findIndex((t) => re.test(t));
  return i < 0 ? 0 : l.tops[i];
};

/**
 * The span from the first line that matches `first` to the first line at or
 * after it that matches `last` - a run of turns, so a joke that takes four
 * turns to land can be drawn as one block instead of a single highlighted row.
 * Matched by words for the same reason findLine is: a new turn must not be able
 * to silently move the box.
 */
export const findBlock = (l: Lines | null, first: RegExp, last: RegExp) => {
  if (!l) return null;
  const a = l.texts.findIndex((t) => first.test(t));
  if (a < 0) return null;
  const rel = l.texts.slice(a).findIndex((t) => last.test(t));
  const b = rel < 0 ? a : a + rel;
  return {top: l.tops[a], bottom: l.bottoms[b]};
};

export const ConversationPage: React.FC<{
  page: string;
  scrollY: number;
  height: number;
  onMeasured: (l: Lines) => void;
}> = ({page, scrollY, height, onMeasured}) => {
  const ref = useRef<HTMLIFrameElement>(null);
  const [handle] = useState(() => delayRender(`measuring ${page}`));
  const [docHeight, setDocHeight] = useState(3000);

  const measure = useCallback(() => {
    const doc = ref.current?.contentDocument;
    if (!doc) return;

    // The page honours prefers-color-scheme and the render host has its own
    // preference, which is nobody's business here. Pin the light palette, the
    // same way the report is pinned in ReportPage.
    const force = doc.createElement('style');
    force.textContent = `:root{color-scheme:light}
      html,body{background:#f7f4ef!important}`;
    doc.head.appendChild(force);

    const top = (el: Element) =>
      (el as HTMLElement).getBoundingClientRect().top + (doc.documentElement.scrollTop || 0);

    const els = Array.from(doc.querySelectorAll('.line'));
    const tops = els.map(top);
    const bottoms = els.map((el) => top(el) + (el as HTMLElement).getBoundingClientRect().height);
    const texts = els.map((e) => (e.textContent || '').trim());
    const h = doc.documentElement.scrollHeight;
    setDocHeight(h);
    onMeasured({docHeight: h, tops, bottoms, texts});
    continueRender(handle);
  }, [handle, onMeasured]);

  return (
    <iframe
      ref={ref}
      src={staticFile(`pages/${page}.html`)}
      onLoad={measure}
      scrolling="no"
      style={{
        width: PAGE_W,
        height: Math.max(docHeight, height),
        border: 'none',
        background: theme.paper,
        position: 'absolute',
        top: -scrollY,
        left: 0,
      }}
    />
  );
};

/**
 * A device, because a web page floating on a dark ground reads as a slide and a
 * page inside a handset reads as a thing somebody is holding. The glass is the
 * product's page at its phone width; everything around it is furniture.
 */
export const Device: React.FC<{
  width: number;
  height: number;
  children: React.ReactNode;
}> = ({width, height, children}) => {
  const bezel = 16;
  return (
    <div
      style={{
        width: width + bezel * 2,
        height: height + bezel * 2,
        borderRadius: 46,
        padding: bezel,
        background: 'linear-gradient(160deg, #2c2822 0%, #16130f 55%, #221e18 100%)',
        boxShadow:
          '0 0 0 1px rgba(240,236,229,0.09), 0 40px 90px rgba(0,0,0,0.65), 0 0 140px rgba(0,0,0,0.5)',
      }}
    >
      <div
        style={{
          width,
          height,
          borderRadius: 32,
          overflow: 'hidden',
          position: 'relative',
          background: theme.paper,
        }}
      >
        {children}
        {/* A scrolling page is always cut mid-line at top and bottom. Slicing a
            sentence in half looks like a rendering fault; dissolving it into the
            paper looks like reading. */}
        <div
          style={{
            position: 'absolute',
            inset: 0,
            pointerEvents: 'none',
            background: `linear-gradient(180deg, ${theme.paper} 0%, rgba(247,244,239,0) 7%,
              rgba(247,244,239,0) 92%, ${theme.paper} 100%)`,
          }}
        />
        {/* the light the glass catches - it stops the screen looking pasted on */}
        <div
          style={{
            position: 'absolute',
            inset: 0,
            pointerEvents: 'none',
            background:
              'linear-gradient(115deg, rgba(255,255,255,0.13) 0%, rgba(255,255,255,0) 26%, rgba(0,0,0,0) 74%, rgba(0,0,0,0.10) 100%)',
          }}
        />
      </div>
    </div>
  );
};
